Repository eslint/css, pull requests merged in 2024-11, with the labels that each got.

#2 feat: CSS language plugin
  .gitattributes
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/new-rule.yml
  .github/ISSUE_TEMPLATE/rule-change.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/bun-test.yml
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .github/workflows/update-readme.yml
  .gitignore
  .npmrc
  .prettierignore
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  docs/rules/no-empty-blocks.md
  eslint.config.js
  jsr.json
  package.json
  prettier.config.js
  release-please-config.json
  rollup.config.js
  src/index.js
  src/languages/css-language.js
  src/languages/css-source-code.js
  src/languages/css-visitor-keys.js
  src/rules/no-empty-blocks.js
  tests/languages/css-language.test.js
  tests/languages/css-source-code.test.js
  tests/package/exports.js
  tests/plugin/eslint.test.js
  tests/rules/no-empty-blocks.test.js
  tools/commit-readme.sh
  tools/dedupe-types.js
  tools/update-readme.js
  tools/update-rules-docs.js
  tsconfig.esm.json
  tsconfig.json
Labels: feature, accepted

#4 feat: Add no-duplicate-imports rule
  README.md
  docs/rules/no-duplicate-imports.md
  src/index.js
  src/rules/no-duplicate-imports.js
  tests/rules/no-duplicate-imports.test.js
Labels: feature

#8 test: Ensure all rules are exported
  tests/package/exports.js
  tests/plugin/eslint.test.js
Labels: chore

#7 feat: no-unknown-at-rules rule
  README.md
  docs/rules/no-unknown-at-rules.md
  src/index.js
  src/rules/no-unknown-at-rules.js
  tests/rules/no-unknown-at-rules.test.js
Labels: feature

#10 chore: upgrade @eslint/plugin-kit@0.2.3
  package.json
Labels: chore

#11 feat: no-invalid-properties rule
  README.md
  docs/rules/no-invalid-properties.md
  docs/rules/no-unknown-properties.md
  package.json
  src/index.js
  src/rules/no-invalid-properties.js
  src/rules/no-unknown-properties.js
  tests/rules/no-invalid-properties.test.js
  tests/rules/no-unknown-properties.test.js
  tsconfig.json
  typings/LICENSE
  typings/css-tree.d.ts
Labels: feature

#15 chore: use eslint-plugin-eslint-plugin
  README.md
  eslint.config.js
  package.json
  src/rules/no-duplicate-imports.js
  src/rules/no-empty-blocks.js
  src/rules/no-invalid-properties.js
  src/rules/no-unknown-at-rules.js
Labels: chore

#12 feat: no-unknown-at-rules -> no-invalid-at-rules
  README.md
  docs/rules/no-invalid-at-rules.md
  docs/rules/no-unknown-at-rules.md
  src/index.js
  src/rules/no-invalid-at-rules.js
  src/rules/no-invalid-properties.js
  src/rules/no-unknown-at-rules.js
  src/util.js
  tests/rules/no-invalid-at-rules.test.js
Labels: feature, accepted, breaking

#16 fix: add type tests
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  docs/rules/no-duplicate-imports.md
  docs/rules/no-empty-blocks.md
  docs/rules/no-invalid-at-rules.md
  docs/rules/no-invalid-properties.md
  package.json
  src/index.js
  src/rules/no-duplicate-imports.js
  src/rules/no-empty-blocks.js
  src/rules/no-invalid-at-rules.js
  src/rules/no-invalid-properties.js
  tests/types/tsconfig.json
  tests/types/types.test.ts
Labels: bug

#22 chore: Remove release-as from release-please-config.json
  release-please-config.json
Labels: chore
