Repository eslint/css, pull requests merged in 2025-03, with the labels that each got.

#63 feat: add prefer-logical-properties rule
  README.md
  docs/rules/prefer-logical-properties.md
  src/index.js
  src/rules/prefer-logical-properties.js
  tests/rules/prefer-logical-properties.test.js
Labels: feature, contributor pool

#82 fix: compute baseline status of individual features
  package.json
  src/data/baseline-data.js
  tests/rules/require-baseline.test.js
  tools/generate-baseline.js
Labels: bug

#87 feat: CSS nesting baseline support
  src/rules/require-baseline.js
  tests/rules/require-baseline.test.js
Labels: feature

#74 fix: expand supported types in baseline-data
  package.json
  src/data/baseline-data.js
  tests/rules/require-baseline.test.js
  tools/generate-baseline.js
Labels: bug

#92 fix: Add support period-separated layer names in use-layers rule
  docs/rules/use-layers.md
  src/rules/use-layers.js
  tests/rules/use-layers.test.js
Labels: bug, contributor pool

#93 fix: Don't check class names in require-baseline
  src/rules/require-baseline.js
  tests/rules/require-baseline.test.js
Labels: bug

#95 chore: Upgrade @eslint/css-tree
  package.json
Labels: accepted, chore

#97 fix: Catch more parse errors
  package.json
  src/languages/css-language.js
  tests/languages/css-language.test.js
Labels: bug

#100 feat!: Rename require-basline -> use-baseline
  README.md
  docs/rules/use-baseline.md
  src/index.js
  src/rules/use-baseline.js
  tests/rules/use-baseline.test.js
Labels: feature, breaking

#101 docs: Add `use-baseline` URL
  eslint.config.js
  src/rules/use-baseline.js
Labels: documentation

#102 docs: Better Baseline comms in use-baseline.md
  docs/rules/use-baseline.md
Labels: documentation
