Repository eslint/css, pull requests merged in 2025-05, with the labels that each got.

#121 docs: Update README to use defineConfig
  README.md
Labels: documentation

#124 feat: add no-important rule
  README.md
  docs/rules/no-important.md
  src/index.js
  src/rules/no-important.js
  src/util.js
  tests/rules/no-important.test.js
Labels: feature

#131 docs: Add instructions for editor setup
  README.md
Labels: documentation

#128 feat: allow custom descriptors in no-invalid-at-rules
  src/rules/no-invalid-at-rules.js
  tests/rules/no-invalid-at-rules.test.js
Labels: feature, contributor pool

#130 feat: Update Baseline data
  package.json
  src/data/baseline-data.js
Labels: feature, accepted

#134 chore: Update CSSTree
  package.json
Labels: chore

#132 build: Generate social media changelog announcement
  .github/workflows/release-please.yml
Labels: build

#136 build: Announce releases in Discord
  .github/workflows/release-please.yml
Labels: accepted, build

#140 docs: Update README with prerequisites
  README.md
Labels: documentation, accepted

#133 feat: add `relative-font-units` rule
  README.md
  docs/rules/relative-font-units.md
  src/index.js
  src/rules/relative-font-units.js
  tests/rules/relative-font-units.test.js
Labels: feature, accepted

#145 chore: update ESLint config to use `defineConfig`
  eslint.config.js
  package.json
  tools/update-readme.js
Labels: chore

#150 docs: add keyframe !important documentation
  docs/rules/no-important.md
  tests/rules/no-important.test.js
Labels: documentation, contributor pool

#144 docs: improve documentation with inline config comments
  docs/rules/no-duplicate-imports.md
  docs/rules/no-empty-blocks.md
  docs/rules/no-important.md
  docs/rules/no-invalid-at-rules.md
  docs/rules/no-invalid-properties.md
  docs/rules/prefer-logical-properties.md
  docs/rules/relative-font-units.md
  docs/rules/use-baseline.md
  docs/rules/use-layers.md
Labels: documentation, accepted

#154 chore: Update new rule issue template
  .github/ISSUE_TEMPLATE/new-rule.yml
Labels: accepted, chore
