Repository eslint/css, pull requests merged in 2025-09, with the labels that each got.

#253 chore: update eslint-config-eslint
  package.json
Labels: chore

#258 refactor: move option access from visitors in prefer-logical-properties
  src/rules/prefer-logical-properties.js
Labels: accepted, chore

#259 test: add `exactOptionalPropertyTypes` option to type test
  tests/types/tsconfig.json
Labels: chore

#261 test: use `.test` suffix for test files
  package.json
  tests/package/exports.test.js
  tests/types/tsconfig.json
Labels: accepted, chore

#268 ci: centralize `update-readme` workflow
  .github/workflows/update-readme.yml
  .gitignore
  package.json
  tools/commit-readme.sh
  tools/update-readme.js
Labels: accepted, build

#279 chore: update rollup to v4.52.3
  package.json
Labels: chore

#272 refactor: replace `findOffsets` helper with native methods
  src/rules/no-important.js
  src/util.js
Labels: accepted, chore
