Repository eslint/css, pull requests merged in 2025-01, with the labels that each got.

#38 feat: Add tolerant parsing mode
  README.md
  package.json
  src/languages/css-language.js
  tests/languages/css-language.test.js
  tests/plugin/eslint.test.js
Labels: feature

#27 feat: Add use-layers rule
  README.md
  docs/rules/use-layers.md
  package.json
  src/index.js
  src/rules/use-layers.js
  tests/rules/use-layers.test.js
Labels: feature, accepted

#44 fix: make types usable in CommonJS
  .npmrc
  jsr.json
  package.json
  tests/types/cjs-import.test.cts
  tests/types/tsconfig.json
  tsconfig.json
  typings/css-tree/LICENSE
  typings/css-tree/index.d.ts
  typings/css-tree/package.json
Labels: bug
