Repository eslint/css, pull requests merged in 2025-04, with the labels that each got.

#107 ci: use standalone Corepack for Yarn
  .github/workflows/ci-build-all-pm.yml
Labels: build

#108 ci: use pnpm/action-setup for pnpm
  .github/workflows/ci-build-all-pm.yml
Labels: build

#106 ci: disable fail-fast in matrix
  .github/workflows/ci.yml
Labels: build

#113 docs: Fix typo on CHANGELOG
  CHANGELOG.md
Labels: documentation

#103 feat: Type checking for all APIs and rules
  jsr.json
  package.json
  rollup.config.js
  src/index.js
  src/languages/css-language.js
  src/languages/css-source-code.js
  src/rules/no-duplicate-imports.js
  src/rules/no-empty-blocks.js
  src/rules/no-invalid-at-rules.js
  src/rules/no-invalid-properties.js
  src/rules/prefer-logical-properties.js
  src/rules/use-baseline.js
  src/rules/use-layers.js
  src/types.ts
  src/util.js
  tools/dedupe-types.js
  tools/update-cts.js
Labels: feature, accepted
