Repository eslint/css, pull requests merged in 2025-08, with the labels that each got.

#222 fix: make relative-font-units unit matching case-insensitive
  src/rules/relative-font-units.js
  tests/rules/relative-font-units.test.js
Labels: bug, accepted, contributor pool

#231 fix: allow any type for `meta.docs.recommended` in custom rules
  package.json
  tests/types/types.test.ts
Labels: bug, accepted

#232 fix: make no-invalid-properties var() case-insensitive
  src/rules/no-invalid-properties.js
  tests/rules/no-invalid-properties.test.js
Labels: bug, accepted, contributor pool

#236 test: add tests for recommended rules
  tests/plugin/eslint.test.js
Labels: accepted, chore

#230 ci: add `stale.yml`
  .github/workflows/stale.yml
Labels: accepted, build

#228 feat: add allow-list options for at-rules, properties, and selectors
  docs/rules/use-baseline.md
  src/rules/use-baseline.js
  tests/rules/use-baseline.test.js
Labels: feature, accepted, contributor pool

#229 refactor: update eslint-config-eslint
  package.json
  src/languages/css-source-code.js
  src/rules/no-invalid-properties.js
  tools/dedupe-types.js
  tools/update-readme.js
Labels: accepted, chore, contributor pool

#243 fix: Upgrade @eslint/css-tree
  package.json
Labels: bug, accepted
