Repository eslint/css, pull requests merged in 2025-07, with the labels that each got.

#171 feat: add no-invalid-at-rule-placement rule
  README.md
  docs/rules/no-invalid-at-rule-placement.md
  src/index.js
  src/rules/no-invalid-at-rule-placement.js
  tests/rules/no-invalid-at-rule-placement.test.js
Labels: feature, accepted, contributor pool

#194 docs: remove `PULL_REQUEST_TEMPLATE.md` in favor of centralized template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#198 chore: enable skipLibCheck
  tsconfig.json
Labels: accepted, chore

#203 refactor: use `CustomRuleDefinitionType` in `CSSRuleDefinition`
  package.json
  src/types.ts
Labels: accepted, chore

#143 feat: add new rule `no-duplicate-keyframe-selectors`
  .gitignore
  README.md
  docs/rules/no-duplicate-keyframe-selectors.md
  eslint.config.js
  src/rules/no-duplicate-keyframe-selectors.js
  tests/rules/no-duplicate-keyframe-selectors.test.js
Labels: feature, accepted

#206 refactor: add missing type annotations to variables
  src/languages/css-source-code.js
Labels: chore

#216 feat: add autofix to no-duplicate-imports rule
  src/rules/no-duplicate-imports.js
  tests/rules/no-duplicate-imports.test.js
Labels: feature, accepted

#217 feat: add suggestion to no-important rule to remove !important flag
  src/rules/no-important.js
  tests/rules/no-important.test.js
Labels: feature, accepted, contributor pool
