Repository eslint/css, pull requests merged in 2025-06, with the labels that each got.

#161 chore: cleanup gitignore & add .vsocde
  .gitignore
Labels: accepted, chore

#165 docs: change the incorrect command in the README.md
  README.md
Labels: documentation, accepted

#170 chore: update lint-staged to use predefined script
  package.json
Labels: chore

#173 fix: Upgrade @eslint/css-tree to update syntax support
  package.json
  tests/rules/no-invalid-properties.test.js
Labels: bug

#179 chore: fix wrong JSDoc tag
  src/languages/css-language.js
Labels: chore

#178 feat: no-invalid-properties allowUnknownVariables option
  docs/rules/no-invalid-properties.md
  src/rules/no-invalid-properties.js
  src/util.js
  tests/rules/no-invalid-properties.test.js
Labels: feature, accepted, contributor pool

#169 feat: add no-invalid-named-grid-areas rule
  README.md
  docs/rules/no-invalid-named-grid-areas.md
  src/index.js
  src/rules/no-invalid-named-grid-areas.js
  tests/rules/no-invalid-named-grid-areas.test.js
Labels: feature, accepted, contributor pool
