Repository eslint/css, pull requests merged in 2025-02, with the labels that each got.

#33 feat: require-baseline rule
  README.md
  docs/rules/require-baseline.md
  package.json
  src/data/README.md
  src/data/baseline-data.js
  src/data/colors.js
  src/index.js
  src/rules/require-baseline.js
  tests/rules/require-baseline.test.js
  tools/generate-baseline.js
  tools/update-rules-docs.js
Labels: feature, accepted

#52 fix: require-baseline should not warn for cursor property
  docs/rules/require-baseline.md
  src/data/baseline-data.js
  tests/rules/require-baseline.test.js
  tools/generate-baseline.js
Labels: bug, accepted

#49 feat: Add support for media conditions in require-baseline rule
  docs/rules/require-baseline.md
  src/data/baseline-data.js
  src/rules/require-baseline.js
  tests/rules/require-baseline.test.js
  tools/generate-baseline.js
Labels: feature, contributor pool

#59 ci: add package manager install checks
  .github/workflows/ci-build-all-pm.yml
Labels: build

#61 feat: add selector support to require-baseline
  docs/rules/require-baseline.md
  src/rules/require-baseline.js
  tests/rules/require-baseline.test.js
Labels: feature, contributor pool

#71 docs: add jsr and experimental to Deno command
  README.md
Labels: documentation
